# Site settings
title: Let us Calculate!
description: "Random Thoughts on Mathematics and Machine Learning"
url: "https://bobflagg.github.io"

name: Bob Flagg, Data Scientist and Mathematician
markdown: kramdown


# Secondary Parameters
header-img: img/home-bg.jpg
headercolor: "#504442"

# Jekyll Settings

defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      header-img: "img/home-bg.jpg"


